### PR TITLE
Adding support for a `tree(skip)` field attribute

### LINKED ISSUE #182: add `#[tree(skip)]`
to not require dummy `Serialize/Deserialize` impls

### PR DESCRIPTION
**Pull request by ryan-summers**
Adds support for skipping fields in a miniconf tree.

Fixes #182

### CODE REVIEW

**Comment by ryan-summers** [comment]
Thanks for the cleanup - the refactor to an `Option` on new() was what I was contemplating as well. I like the approach :)

**Review by jordens — APPROVED** [review]
@ryan-summers I made a couple tweaks.

**Comment by ryan-summers** [comment]
@jordens We seem to be hitting a ton of ICEs when compiling on stable for some reason... I don't see these locally with my rustc 1.72.0

**Comment by jordens** [comment]
https://github.com/rust-lang/rust/issues/116662

**Pull request merged**
