### PR TITLE
Add update_or_process() for unexpected message topics

### PR DESCRIPTION
**Pull request by dnadlinger**
Includes #36.

### CODE REVIEW

**Comment by dnadlinger** [comment]
This is an alternative to the approach proposed in #35, whereby miniconf still owns the minimq client, but accepts an unexpected topic handler as a closure that can be used to respond to non-settings topics. This is still a bit messy, as the client code also effectively needs to duplicate the (re-)subscription handling code.

I'm not sure what the best design is here, but see https://github.com/dnadlinger/stabilizer/commit/de189c2f5c9469fc4cca3ff5afaa33db1a8ba6db for a quickly hacked-together use case of this (adds a "query" topic which can be used to read back a continuously updating value).

**Comment by ryan-summers** [comment]
Closing. MQTT functionality has been removed from this library - if we want this functionality in Stabilizer, we can add it there directly if desired, although I believe the re-architecture makes this redundant. Let me know if you have any issues!

**Comment by dnadlinger** [comment]
Was about to do that just now, literally was already on the page. :)

Adding a hook to stabilizer's `net` to allow people to adding additional topics in additional binaries without changes to the shared code would probably still be interesting, though.

**Comment by ryan-summers** [comment]
By the way - thanks for the feedback - definitely helped with figuring out the right re-architecture :)

**Pull request closed without merging**
